export const usersActionTypes = {
    FETCH_ITEMS:'FETCH_ITEMS',
    ADD_TO_CART:'ADD_TO_CART',
    UPDATE_TO_CART:'UPDATE_TO_CART',
    DELETE_FROM_CART:'DELETE_FROM_CART',
    CLEAR_CART:'CLEAR_CART',
    UPDATE_PRICE:'UPDATE_PRICE'
}